<template>
        <v-chart
            ref="chart"
            :initOptions="initOptions"
            :options="options"
            autoresize/>
</template>
<style>
.echarts {
  width: 100%;
  height: 100%;
}
</style>
<script lang="ts">
import Vue from 'vue'
import { Component, Ref } from "vue-property-decorator"

// chart
import 'echarts/lib/chart/line'
import 'echarts/lib/component/tooltip'
import 'echarts/lib/component/grid'
import 'echarts/lib/component/toolbox'

@Component
export default class StepLine extends Vue{

  @Ref('chart') readonly chart!: any
    @Ref('container') readonly container!: HTMLDivElement

    get initOptions() {
        return {
            dom: this.container
        }
    }
  
  // printImage() {
  //   return this.chart.getDataURL({type: "png", backgroundColor: '#fff'})
  // }

  // HACK für Demo!!!
  get options() {
    return {
    toolbox: {
        showTitle: false,
        orient: 'vertical',
        feature: {
            saveAsImage: {show: true, title: 'Download', name: 'Gangliniendiagramm'},
            // dataView: {show: true, readOnly: true, title: 'Datenansicht', lang: ['Datenansicht', 'zurück', 'refresh']},
        },
        tooltip: {
            show: true,
            position: 'top',
        },
    },
    tooltip: {
        trigger: 'axis'
    },
    legend: {
        data: ['PKW', 'Schwerverkehr', 'Güterverkehr', 'Gesamt']
    },
    grid: {
        left: '7%',
        right: '5%',
        bottom: '5%',
        containLabel: false
    },
    xAxis: {
        type: 'category',
        data: [
            '0.1',
            '0.2',
            '0.3',
            '0.4',
            '1.1',
            '1.2',
            '1.3',
            '1.4',
            '2.1',
            '2.2',
            '2.3',
            '2.4',
            '3.1',
            '3.2',
            '3.3',
            '3.4',
            '4.1',
            '4.2',
            '4.3',
            '4.4',
            '5.1',
            '5.2',
            '5.3',
            '5.4',
            '6.1',
            '6.2',
            '6.3',
            '6.4',
            '7.1',
            '7.2',
            '7.3',
            '7.4',
            '8.1',
            '8.2',
            '8.3',
            '8.4',
            '9.1',
            '9.2',
            '9.3',
            '9.4',
            '10.1',
            '10.2',
            '10.3',
            '10.4',
            '11.1',
            '11.2',
            '11.3',
            '11.4',
            '12.1',
            '12.2',
            '12.3',
            '12.4',
            '13.1',
            '13.2',
            '13.3',
            '13.4',
            '14.1',
            '14.2',
            '14.3',
            '14.4',
            '15.1',
            '15.2',
            '15.3',
            '15.4',
            '16.1',
            '16.2',
            '16.3',
            '16.4',
            '17.1',
            '17.2',
            '17.3',
            '17.4',
            '18.1',
            '18.2',
            '18.3',
            '18.4',
            '19.1',
            '19.2',
            '19.3',
            '19.4',
            '20.1',
            '20.2',
            '20.3',
            '20.4',
            '21.1',
            '21.2',
            '21.3',
            '21.4',
            '22.1',
            '22.2',
            '22.3',
            '22.4',
            '23.1',
            '23.2',
            '23.3',
            '23.4'
            ],
        splitArea: {
            show: true
        }
    },
    yAxis: {
        type: 'value'
    },
    series: [
        {
            name: 'PKW',
            type: 'line',
            step: 'middle',
            data: [
                30,
                39,
                27,
                46,
                25,
                8,
                20,
                2,
                15,
                43,
                56,
                49,
                80,
                53,
                90,
                53,
                69,
                57,
                63,
                95,
                89,
                128,
                188,
                81,
                143,
                143,
                131,
                208,
                120,
                113,
                198,
                121,
                228,
                246,
                109,
                180,
                217,
                105,
                119,
                168,
                112,
                162,
                123,
                106,
                71,
                125,
                121,
                59,
                68,
                96,
                52,
                78,
                78,
                92,
                83,
                67,
                34,
                60,
                58,
                42,
                107,
                127,
                134,
                64,
                169,
                74,
                188,
                161,
                148,
                160,
                204,
                225,
                145,
                196,
                138,
                108,
                81,
                175,
                91,
                78,
                149,
                113,
                87,
                112,
                45,
                67,
                55,
                65,
                22,
                12,
                49,
                34,
                6,
                19,
                24,
                2
                ]
        },
        {
            name: 'Schwerverkehr',
            type: 'line',
            step: 'middle',
            data: [
                2,
                4,
                2,
                5,
                1,
                1,
                5,
                2,
                6,
                5,
                8,
                9,
                10,
                10,
                9,
                7,
                8,
                16,
                9,
                10,
                18,
                21,
                20,
                21,
                16,
                12,
                16,
                22,
                24,
                19,
                28,
                21,
                34,
                21,
                17,
                18,
                28,
                14,
                23,
                17,
                19,
                13,
                16,
                10,
                17,
                14,
                6,
                9,
                5,
                6,
                9,
                8,
                12,
                6,
                5,
                12,
                12,
                12,
                7,
                9,
                15,
                9,
                16,
                18,
                10,
                19,
                12,
                16,
                17,
                21,
                25,
                15,
                28,
                18,
                25,
                14,
                19,
                21,
                10,
                12,
                10,
                14,
                7,
                8,
                9,
                9,
                7,
                10,
                3,
                5,
                3,
                3,
                3,
                3,
                6,
                6
                ]
        },
        {
            name: 'Güterverkehr',
            type: 'line',
            step: 'middle',
            data: [
                2,
                10,
                0,
                2,
                11,
                11,
                5,
                1,
                6,
                9,
                8,
                8,
                16,
                17,
                19,
                18,
                30,
                15,
                14,
                19,
                23,
                31,
                46,
                23,
                29,
                46,
                53,
                43,
                31,
                45,
                52,
                65,
                32,
                46,
                51,
                28,
                28,
                36,
                22,
                25,
                45,
                21,
                38,
                20,
                34,
                23,
                20,
                16,
                11,
                12,
                23,
                10,
                21,
                20,
                12,
                22,
                19,
                16,
                22,
                19,
                14,
                26,
                28,
                36,
                23,
                36,
                39,
                45,
                41,
                51,
                34,
                45,
                58,
                24,
                52,
                31,
                20,
                26,
                16,
                32,
                26,
                25,
                24,
                13,
                10,
                13,
                19,
                11,
                16,
                4,
                2,
                0,
                11,
                8,
                2,
                10
                ]
        },
        {
            name: 'Gesamt',
            type: 'line',
            step: 'middle',
            data: [
                34,
                53,
                29,
                53,
                37,
                20,
                30,
                5,
                27,
                57,
                72,
                66,
                106,
                80,
                118,
                78,
                107,
                88,
                86,
                124,
                130,
                180,
                254,
                125,
                188,
                201,
                200,
                273,
                175,
                177,
                278,
                207,
                294,
                313,
                177,
                226,
                273,
                155,
                164,
                210,
                176,
                196,
                177,
                136,
                122,
                162,
                147,
                84,
                84,
                114,
                84,
                96,
                111,
                118,
                100,
                101,
                65,
                88,
                87,
                70,
                136,
                162,
                178,
                118,
                202,
                129,
                239,
                222,
                206,
                232,
                263,
                285,
                231,
                238,
                215,
                153,
                120,
                222,
                117,
                122,
                185,
                152,
                118,
                133,
                64,
                89,
                81,
                86,
                41,
                21,
                54,
                37,
                20,
                30,
                32,
                18
                ]
        }
    ]
}
  }

}
</script>